config/routes.rb
Rails.application.routes.draw do
  resources :places

  devise_for :users
  
  root to: "home#index"

  resources :presents

  resources :movies

  resources :people

  resources :books

end

app/models/present.rb
class Present < ActiveRecord::Base

belongs_to :user

end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController
  before_action :set_present, only: [:show, :edit, :update, :destroy]

  # GET /presents
  # GET /presents.json
  def index
    @presents = Present.all
  end

  # GET /presents/1
  # GET /presents/1.json
  def show
  end

  # GET /presents/new
  def new
    @present = Present.new
  end

  # GET /presents/1/edit
  def edit
  end

  # POST /presents
  # POST /presents.json
  def create
    @present = Present.new(present_params)

    respond_to do |format|
      if @present.save
        format.html { redirect_to @present, notice: 'Present was successfully created.' }
        format.json { render :show, status: :created, location: @present }
      else
        format.html { render :new }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presents/1
  # PATCH/PUT /presents/1.json
  def update
    respond_to do |format|
      if @present.update(present_params)
        format.html { redirect_to @present, notice: 'Present was successfully updated.' }
        format.json { render :show, status: :ok, location: @present }
      else
        format.html { render :edit }
        format.json { render json: @present.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presents/1
  # DELETE /presents/1.json
  def destroy
    @present.destroy
    respond_to do |format|
      format.html { redirect_to presents_url, notice: 'Present was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_present
      @present = Present.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def present_params
      params.require(:present).permit(:present, :giftee, :occasion)
    end
end

app/helpers/presents_helper.rb
module PresentsHelper
end

app/views/presents/_form.html.erb
<div class="col-sm-4 col-sm-offset-4">
  <%= form_for(@present) do |f| %>
    <% if @present.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@present.errors.count, "error") %> prohibited this present from being saved:</h2>

        <ul>
        <% @present.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :present %><br>
      <%= f.text_field :present %>
    </div>
    <div class="field">
      <%= f.label :giftee %><br>
      <%= f.text_field :giftee %>
    </div>
    <div class="field">
      <%= f.label :occasion %><br>
      <%= f.text_field :occasion %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/presents/edit.html.erb
<h1>Editing present</h1>

<%= render 'form' %>

<%= link_to 'Show', @present %> |
<%= link_to 'Back', presents_path %>

app/views/presents/index.html.erb
<div class="col-sm-4 col-sm-offset-4">
  <h1>Presents to make</h1>

  <table>
    <thead>
      <tr>
        <th>Present</th>
        <th>Giftee</th>
        <th>Occasion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @presents.each do |present| %>
        <tr>
          <td><%= present.present %></td>
          <td><%= present.giftee %></td>
          <td><%= present.occasion %></td>
          <td><%= link_to 'Show', present %></td>
          <td><%= link_to 'Edit', edit_present_path(present) %></td>
          <td><%= link_to 'Destroy', present, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= button_to('New Present', new_present_path, class: 'btn btn-large btn-info') %>
</div>

app/views/presents/new.html.erb
<div class="col-sm-4 col-sm-offset-4">
	<h1>New present</h1>
</div>

<%= render 'form' %>

app/views/presents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Present:</strong>
  <%= @present.present %>
</p>

<p>
  <strong>Giftee:</strong>
  <%= @present.giftee %>
</p>

<p>
  <strong>Occasion:</strong>
  <%= @present.occasion %>
</p>

<%= link_to 'Edit', edit_present_path(@present) %> |
<%= link_to 'Back', presents_path %>