config/routes.rb
Rails.application.routes.draw do
  resources :places

  devise_for :users
  
  root to: "home#index"

  resources :presents

  resources :movies

  resources :people

  resources :books

end

app/models/person.rb
class Person < ActiveRecord::Base

belongs_to :user

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :reason, :channel, :deadline)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class="col-sm-4 col-sm-offset-4">
  <%= form_for(@person) do |f| %>
    <% if @person.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

        <ul>
        <% @person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :reason %><br>
      <%= f.text_area :reason %>
    </div>
    <div class="field">
      <%= f.label :channel %><br>
      <%= f.text_field :channel %>
    </div>
    <div class="field">
      <%= f.label :deadline %><br>
      <%= f.date_select :deadline %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<div class="col-sm-4 col-sm-offset-4">
  <h1>People to contact</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Reason</th>
        <th>Channel</th>
        <th>Deadline</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @people.each do |person| %>
        <tr>
          <td><%= person.name %></td>
          <td><%= person.reason %></td>
          <td><%= person.channel %></td>
          <td><%= person.deadline %></td>
          <td><%= link_to 'Show', person %></td>
          <td><%= link_to 'Edit', edit_person_path(person) %></td>
          <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= button_to('New Person', new_person_path, class: 'btn btn-large btn-info') %>
</div>

app/views/people/new.html.erb
<div class="col-sm-4 col-sm-offset-4">
	<h1>New person</h1>
</div>
<%= render 'form' %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @person.reason %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @person.channel %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @person.deadline %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>