config/routes.rb
Rails.application.routes.draw do
  resources :places

  devise_for :users
  
  root to: "home#index"

  resources :presents

  resources :movies

  resources :people

  resources :books

end

app/models/place.rb
class Place < ActiveRecord::Base

belongs_to :user

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params[:place]
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<div class="col-sm-4 col-sm-offset-4">
  <%= form_for(@place) do |f| %>
    <% if @place.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

        <ul>
        <% @place.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :location %><br>
      <%= f.text_field :location %>
    </div>
    <div class="field">
      <%= f.label :country %><br>
      <%= f.text_area :country %>
    </div>
    <div class="field">
      <%= f.label :recommended_by %><br>
      <%= f.text_field :recommended_by %>
    </div>
    <div class="field">
      <%= f.label :reminder_date %><br>
      <%= f.date_select :reminder_date %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<div class="col-sm-4 col-sm-offset-4">  
  <h1>Places to visit</h1>

  <table>
    <thead>
      <tr>
        <th>Location</th>
        <th>Country</th>
        <th>Recommended_by</th>
        <th>Reminder date</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @places.each do |place| %>
        <tr>
          <td><%= place.location %></td>
          <td><%= place.country %></td>
          <td><%= place.recommended_by %></td>
          <td><%= place.reminder_date %></td>
          <td><%= link_to 'Show', place %></td>
          <td><%= link_to 'Edit', edit_place_path(place) %></td>
          <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= button_to('New Place', new_place_path, class: 'btn btn-large btn-info') %>
</div>

app/views/places/new.html.erb
<div class="col-sm-4 col-sm-offset-4">
	<h1>New place</h1>
</div>

<%= render 'form' %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>